name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install pydantic_settings
        # pip install pytest pytest-cov

    - name: Start Uvicorn in background
      run: |
        cd backend
        nohup python -m uvicorn app.main:app --host 127.0.0.1 --port 8000 &
        sleep 5  # give it a moment to start

    - name: Test app is up
      run: |
        curl --fail http://127.0.0.1:8000/ || (echo "App did not start" && exit 1)

  frontend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        cd frontend
        npm install

    - name: Run linter
      run: |
        cd frontend
        npm run lint

    # - name: Run tests
    #   run: |
    #     cd frontend
    #     npm run test:unit